//loading
const START_LOADING = 'START_LOADING'
const STOP_LOADING = 'STOP_LOADING'

//snackbar
const ADD_NOTIFICATION = 'ADD_NOTIFICATION'
const REMOVE_NOTIFICATION = 'REMOVE_NOTIFICATION'

//mission control
const UPDATE_MISSION = 'UPDATE_MISSION'
const UPDATE_ROVER = 'UPDATE_ROVER'
const RESET_MISSION = 'RESET_MISSION'
const UPDATE_MODE = 'UPDATE_MODE'
const UPDATE_STATUS = 'UPDATE_STATUS'
const UPDATE_GRID = 'UPDATE_GRID'
const SET_CURRENT_MOVE = 'SET_CURRENT_MOVE'
const SET_CURRENT_ROVER = 'SET_CURRENT_ROVER'

//console logging
const ADD_LOG = 'ADD_LOG'

export default {
  UPDATE_MODE,
  UPDATE_STATUS,
  UPDATE_ROVER,
  UPDATE_MISSION,
  SET_CURRENT_MOVE,
  SET_CURRENT_ROVER,
  STOP_LOADING,
  ADD_NOTIFICATION,
  REMOVE_NOTIFICATION,
  START_LOADING,
  UPDATE_GRID,
  RESET_MISSION,
  ADD_LOG,
}
